### ISSUE TITLE
Type inference can fail when using type classes

### ISSUE THREAD

**Issue by tfausak** [tfausak/thran#1]
It is possible for type inference to fail when using type classes. I created [a Gist](https://gist.github.com/tfausak/2e4434260d5f59a00ea2873b5aa85e14) that includes the original PureScript, the generated Haskell, and the error. Since then I've simplified the example a bit. Consider the following PureScript:

``` purescript
module Example where

class Semigroup a where
  append :: a -> a -> a

infixl 5 append as +

triple :: forall a. Semigroup a => a -> a
triple x = x + x + x
```

 From that, Thran generates this Haskell:

``` haskell
﻿-- Built with psc version 0.10.3.

{-# LANGUAGE DataKinds #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE MagicHash #-}
{-# LANGUAGE NoImplicitPrelude #-}
{-# LANGUAGE NoMonomorphismRestriction #-}

module Example (
  _Semigroup,
  append,
  triple,
) where

import qualified Bookkeeper
import qualified GHC.OverloadedLabels
import qualified GHC.Prim
import qualified Prelude

_Semigroup = (\ append -> (Bookkeeper.emptyBook Bookkeeper.& (GHC.OverloadedLabels.fromLabel (GHC.Prim.proxy# :: GHC.Prim.Proxy# "append")) Bookkeeper.=: append))

append = (\ dict -> (Bookkeeper.get (GHC.OverloadedLabels.fromLabel (GHC.Prim.proxy# :: GHC.Prim.Proxy# "append")) dict))

triple = (\ dictSemigroup -> (\ x -> (((Example.append dictSemigroup) (((Example.append dictSemigroup) x) x)) x)))
```

As far as I can tell, the error message says that GHC can't unify the types between the two calls to `append` in `triple`. It suggests enabling `AllowAmbiguousTypes` to fix it. 

Enabling the extension does work, but apparently it's "[almost never a good idea](http://stackoverflow.com/a/23462397/1274282)." So I'd like to come up with a solution that avoids enabling yet another language extensions (and a questionable one at that). 

Slimming down the generated Haskell, I can still trigger the error with this:

``` haskell
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE OverloadedLabels #-}

import Bookkeeper

semigroup append_ = emptyBook & #append =: append_

append semigroup_ = get #append semigroup_

triple semigroup_ x = (append semigroup_) ((append semigroup_) x x) x
```

Adding some type signatures makes the problem go away. Putting an explicit signature on either `append` or `triple` is enough; putting one on `semigroup` doesn't help.

``` haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE OverloadedLabels #-}
{-# LANGUAGE TypeOperators #-}

import Bookkeeper

type Semigroup a = Book '["append" :=> Append a]

type Append a = a -> a -> a

semigroup :: Append a -> Semigroup a
semigroup append_ = emptyBook & #append =: append_

append :: Semigroup a -> Append a
append semigroup_ = get #append semigroup_

triple :: Semigroup a -> a -> a
triple semigroup_ x = (append semigroup_) ((append semigroup_) x x) x
```

Another way to fix the problem is to capture the result of `append semigroup_` in a local value and share it across usages.

``` haskell
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE OverloadedLabels #-}

import Bookkeeper

semigroup append_ = emptyBook & #append =: append_

append semigroup_ = get #append semigroup_

triple semigroup_ x = let
  append_ = append semigroup_
  in append_ (append_ x x) x
```

Unfortunately neither of these solutions really work for Thran. I can't add type signatures because the type information doesn't exist in the corefn. And pulling the value out into a `let` is technically possible (I think) but seems tedious. 

For the time being I am going to enable `AllowAmbiguousTypes`. But eventually I would like to have a better solution to this problem.

**Comment by pkamenarsky** [comment]
Linking [relevant issue](https://github.com/purescript/purescript/issues/2657) here.
